server:
  servlet:
    encoding:
      force-response: true
spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: localhost
    username: root
    password: password
jwt:
  secret: hello